### PR TITLE
JSRS Migration

### PR DESCRIPTION
**Pull request by fdsgusmao**

### CODE REVIEW

**Comment by fdsgusmao** [comment]
### Goals verified (1 out of 1)

**This capsule runs on intents only**

- Goal: RollDice
```JSON5
intent {
  goal: example.dice.RollResultConcept
  value: example.dice.NumSidesConcept (6)
  value: example.dice.NumDiceConcept (2)
}
```
```JSON5
intent {
  goal: example.dice.RollResultConcept
  value: example.dice.NumSidesConcept (20)
  value: example.dice.NumDiceConcept (2)
}
```
```JSON5
intent {
  goal: example.dice.RollResultConcept
  value: example.dice.NumSidesConcept (12)
  value: example.dice.NumDiceConcept (4)
}
```

**NO ERRORS:** The migration tool successfully migrated this capsule, no extra changes were necessary.

**Comment by fdsgusmao** [comment]
@kangawoo44 @abapayeViv Review please

**Review by kangawoo44 — APPROVED** [review]
LGTM

**Comment by kangawoo44** [comment]
actually, please remove preferred hints under uncategorized hints

**Pull request merged**
