### PR TITLE
Added empty Concept dialog files

### PR DESCRIPTION
**Pull request by abapayeViv**
The Quickstart guide will be updated soon to include a small tutorial for adding user-friendly dialog. The steps require that the base capsule code includes a couple empty dialog files. This PR adds those files.

### CODE REVIEW

**Review by adanis — APPROVED** [review]
thanks Ameya!

**Comment by rogerkibbe** [comment]
LGTM - merging

**Comment by rogerkibbe** [comment]
Looks good - merging

**Review by rogerkibbe — APPROVED** [review]
LGTM

**Pull request merged**
