### PR TITLE
Converge

### PR DESCRIPTION
**Pull request by sarahmolinerroy**

### CODE REVIEW

**Comment by adanis** [comment]
@sarahmolinerroy Can you also do a quick change of removing the `authorization { none }` in the `endpoints.bxb`?

**Comment by sarahmolinerroy** [comment]
@adanis Updated to remove that deprecation warning!

**Review by adanis — APPROVED** [review]
:shipit:

**Comment by rogerkibbe** [comment]
Looks good merging. Jatin on vacation but Anne has approved.

**Pull request merged**
